spring:
  application:
    name: configServer
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/biduzilla/microservices.git"
          search-paths: "configserver/src/main/resources"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
server:
  port: 8071
